// synthesis_stub.sv — TEMPORARY, for Phase 1 dry-run synthesis only
// Instantiates gba_top with all ports stubbed to measure resource usage.
// Will be removed once real core_top.sv integration begins in Phase 2.

module synthesis_stub (
    input  wire        clk100,
    input  wire        reset_n,
    // All outputs exposed to prevent Quartus from optimizing away the core
    output wire        sdram_read_ena,
    output wire [24:0] sdram_read_addr,
    output wire [31:0] bus_out_Din,
    output wire [25:0] bus_out_Adr,
    output wire        bus_out_rnw,
    output wire        bus_out_ena,
    output wire [63:0] SAVE_out_Din,
    output wire [25:0] SAVE_out_Adr,
    output wire        SAVE_out_rnw,
    output wire        SAVE_out_ena,
    output wire        SAVE_out_active,
    output wire [7:0]  SAVE_out_be,
    output wire        save_eeprom,
    output wire        save_sram,
    output wire        save_flash,
    output wire        load_done,
    output wire        Rumble,
    output wire [31:0] GBA_BusReadData,
    output wire [31:0] CyclesMissing,
    output wire [31:0] CyclesVsyncSpeed,
    output wire [31:0] RTC_timestampOut,
    output wire [41:0] RTC_savedtimeOut,
    output wire        RTC_inuse,
    output wire [15:0] sound_out_left,
    output wire [15:0] sound_out_right,
    output wire [31:0] debug_cpu_pc,
    output wire [31:0] debug_cpu_mixed,
    output wire [31:0] debug_irq,
    output wire [31:0] debug_dma,
    output wire [31:0] debug_mem,
    output wire [31:0] pixel_out_x,
    output wire [31:0] pixel_out_y,
    output wire [31:0] pixel_out_addr,
    output wire [17:0] pixel_out_data,
    output wire        pixel_out_we
);

    gba_top #(
        .Softmap_GBA_Gamerom_ADDR(0),
        .Softmap_GBA_WRam_ADDR   (0),
        .Softmap_GBA_FLASH_ADDR  (0),
        .Softmap_GBA_EEPROM_ADDR (0),
        .Softmap_SaveState_ADDR  (0),
        .is_simu                 (1'b0),
        .turbosound              (1'b1)
    ) gba_inst (
        .clk100              (clk100),
        // Settings
        .GBA_on              (reset_n),
        .GBA_lockspeed       (1'b1),
        .GBA_cputurbo        (1'b0),
        .GBA_flash_1m        (1'b0),
        .CyclePrecalc        (16'd100),
        .Underclock          (2'b00),
        .MaxPakAddr          (25'h1FFFFFF),
        .CyclesMissing       (CyclesMissing),
        .CyclesVsyncSpeed    (CyclesVsyncSpeed),
        .SramFlashEnable     (1'b1),
        .memory_remap        (1'b0),
        .increaseSSHeaderCount(1'b0),
        .save_state          (1'b0),
        .load_state          (1'b0),
        .maxpixels           (1'b0),
        .specialmodule       (1'b0),
        .solar_in            (3'b000),
        .tilt                (1'b0),
        .savestate_number    (0),
        // RTC
        .RTC_timestampNew    (1'b0),
        .RTC_timestampIn     (32'h0),
        .RTC_timestampSaved  (32'h0),
        .RTC_savedtimeIn     (42'h0),
        .RTC_saveLoaded      (1'b0),
        .RTC_timestampOut    (RTC_timestampOut),
        .RTC_savedtimeOut    (RTC_savedtimeOut),
        .RTC_inuse           (RTC_inuse),
        // SDRAM (ROM) interface
        .sdram_read_ena      (sdram_read_ena),
        .sdram_read_done     (1'b0),
        .sdram_read_addr     (sdram_read_addr),
        .sdram_read_data     (32'h0),
        .sdram_second_dword  (32'h0),
        // External memory bus (EWRAM + saves)
        .bus_out_Din         (bus_out_Din),
        .bus_out_Dout        (32'h0),
        .bus_out_Adr         (bus_out_Adr),
        .bus_out_rnw         (bus_out_rnw),
        .bus_out_ena         (bus_out_ena),
        .bus_out_done        (1'b0),
        // Save state bus
        .SAVE_out_Din        (SAVE_out_Din),
        .SAVE_out_Dout       (64'h0),
        .SAVE_out_Adr        (SAVE_out_Adr),
        .SAVE_out_rnw        (SAVE_out_rnw),
        .SAVE_out_ena        (SAVE_out_ena),
        .SAVE_out_active     (SAVE_out_active),
        .SAVE_out_be         (SAVE_out_be),
        .SAVE_out_done       (1'b0),
        // BIOS
        .bios_wraddr         (12'h0),
        .bios_wrdata         (32'h0),
        .bios_wr             (1'b0),
        // Save memory type detection
        .save_eeprom         (save_eeprom),
        .save_sram           (save_sram),
        .save_flash          (save_flash),
        .load_done           (load_done),
        // Input (active high)
        .KeyA                (1'b0),
        .KeyB                (1'b0),
        .KeySelect           (1'b0),
        .KeyStart            (1'b0),
        .KeyRight            (1'b0),
        .KeyLeft             (1'b0),
        .KeyUp               (1'b0),
        .KeyDown             (1'b0),
        .KeyR                (1'b0),
        .KeyL                (1'b0),
        .AnalogTiltX         (8'sd0),
        .AnalogTiltY         (8'sd0),
        .Rumble              (Rumble),
        // Debug bus
        .GBA_BusAddr         (28'h0),
        .GBA_BusRnW          (1'b1),
        .GBA_BusACC          (2'b00),
        .GBA_BusWriteData    (32'h0),
        .GBA_BusReadData     (GBA_BusReadData),
        .GBA_Bus_written     (1'b0),
        // Video
        .pixel_out_x         (pixel_out_x),
        .pixel_out_y         (pixel_out_y),
        .pixel_out_addr      (pixel_out_addr),
        .pixel_out_data      (pixel_out_data),
        .pixel_out_we        (pixel_out_we),
        // Audio
        .sound_out_left      (sound_out_left),
        .sound_out_right     (sound_out_right),
        // Debug
        .debug_cpu_pc        (debug_cpu_pc),
        .debug_cpu_mixed     (debug_cpu_mixed),
        .debug_irq           (debug_irq),
        .debug_dma           (debug_dma),
        .debug_mem           (debug_mem)
    );

endmodule
